### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by jinishatejura**
Tiny change in Readme.md

### CODE REVIEW

**Comment by marwahmanbir** [comment]
:wave: Good work! Congratulations for your merged PR! :tada:
Don't forget to star this repository.
Follow ACM BVP on:
Facebook - https://facebook.com/acmbvp
Twitter - https://twitter.com/acmbvp
Instagram - https://instagram.com/acm.bvp

**Comment by jinishatejura** [comment]
Thanks but pls check below :- 
https://twitter.com/JinishaTejura/status/1183018787303411712

**Comment by marwahmanbir** [comment]
Hi Jinisha, this year Hacktoberfest is excluding thousands of repositories that promote easy hike in PR count during October, so as to promote quality contributions (#358). This is not the case with only this repository but tons of other repositories as well (check https://hacktoberfest.digitalocean.com/details).
This is something not in our hands. Also, I'll say that the sole purpose of repository was to help beginners learn Git & GitHub by easy contribution, and that purpose is still fulfilling. Your Tweet is also something that won't help much in this, so I'd suggest you to refrain from blaming us publicly for something that is not in our hands.

**Comment by jinishatejura** [comment]
Not blaming **you**...lets just say **I** took the shortcut & **my** silly trick got backfired !

**Pull request merged**
