### PR TITLE
Create anagrams.cpp

### PR DESCRIPTION
**Pull request by divyansingh**
algorithm to find anagrams

### CODE REVIEW

**Comment by divyansingh** [comment]
anagrams algorithm

**Comment by divyansingh** [comment]
Armstrong number

**Comment by divyansingh** [comment]
swastic_pattern

**Comment by marwahmanbir** [comment]
:wave: Good work! Congratulations for your merged PR! :tada:
Don't forget to star this repository.
Follow ACM BVP on:
Facebook - https://facebook.com/acmbvp
Twitter - https://twitter.com/acmbvp
Instagram - https://instagram.com/acm.bvp

**Pull request merged**
